# Generated by Django 4.1.2 on 2022-11-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=15)),
                ('apellidos', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
                ('tipo_usuario', models.CharField(max_length=20)),
            ],
        ),
    ]
