# Generated by Django 4.1.2 on 2022-11-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='LG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='image')),
            ],
        ),
    ]
