# Generated by Django 4.1.2 on 2022-11-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_abba_challenger_electrodomesticos_mabe_sonido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
