# Generated by Django 4.1.2 on 2022-12-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='correo',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='pago',
            field=models.IntegerField(choices=[(1, 'Pago contra Entrega'), (2, 'Consignacion Bancaria')], default=1, verbose_name=' Medio De Pago'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
