# Generated by Django 4.1.2 on 2022-12-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_compra_correo_alter_compra_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='estado',
        ),
    ]
