# Generated by Django 4.1.2 on 2022-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_catalogo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='pago',
            field=models.IntegerField(default='Pago contra Entrega', verbose_name=' Medio De Pago'),
        ),
    ]
