# Generated by Django 4.1.2 on 2022-12-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_compra_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='pago',
            field=models.CharField(default='Pago contra Entrega', max_length=25, verbose_name=' Medio De Pago'),
        ),
    ]
