# Generated by Django 4.1.2 on 2022-12-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_compra_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='mensaje',
            field=models.TextField(null=True),
        ),
    ]
