# Generated by Django 4.1.2 on 2022-12-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_catalogo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='precio',
            field=models.FloatField(),
        ),
    ]
