# Generated by Django 4.1.2 on 2022-11-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(null=True, verbose_name='Cantidad'),
        ),
    ]
