# Generated by Django 4.1.2 on 2022-12-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
