# Generated by Django 4.1.3 on 2022-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cotizacines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Telefono', models.CharField(max_length=15, null=True, verbose_name='Telefono')),
                ('Correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Dirección', models.CharField(max_length=50, null=True, verbose_name='Direcciòn')),
                ('Producto', models.CharField(max_length=100, null=True, verbose_name='Producto')),
                ('imgproducto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
                ('precio', models.TextField(null=True, verbose_name='Precio')),
                ('Medio_de_pago', models.CharField(max_length=100, null=True, verbose_name='Medio de pago')),
                ('Precio_Total', models.TextField(null=True, verbose_name='Total')),
            ],
        ),
    ]
