# Generated by Django 4.1.2 on 2022-12-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=20, null=True, verbose_name='direccion')),
                ('telefono', models.IntegerField(null=True, verbose_name='telefono')),
                ('correo', models.CharField(max_length=100, null=True, verbose_name='correo')),
                ('pago', models.IntegerField(choices=[(1, 'Pago contra Entrega'), (2, 'Consignacion Bancaria')], default=1, verbose_name='pago')),
            ],
        ),
        migrations.DeleteModel(
            name='cotizacines',
        ),
    ]
