# Generated by Django 4.1.2 on 2022-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_compra_delete_cotizacines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='correo',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='telefono'),
        ),
    ]
