# Generated by Django 4.1.2 on 2022-12-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_compra_correo_alter_compra_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='direccion'),
        ),
    ]
