# Generated by Django 4.1.2 on 2022-12-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_compra_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compra',
        ),
    ]
